using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(false)]
[assembly: ComVisibleAttribute(true)]
[assembly: AssemblyTitleAttribute("Castle.VSNetIntegration.Shared for Microsoft .NET Framework 1.1")]
[assembly: AssemblyDescriptionAttribute("Castle Project Visual Studio Integration Shared Lib")]
[assembly: AssemblyCompanyAttribute("Castle Project")]
[assembly: AssemblyProductAttribute("Castle.VSNetIntegration.Shared")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2004,2005,2006 Castle Project - http://www.castleproject.org")]
[assembly: AssemblyVersionAttribute("2.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("2.0.0.0")]
[assembly: AssemblyFileVersionAttribute("2.0.0.0")]
[assembly: AssemblyKeyFileAttribute("../../../CastleKey.snk")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AllowPartiallyTrustedCallersAttribute()]

