using System;
using System.Reflection;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("Castle.MonoRail.TestSupport for Microsoft .NET Framework 2.0")]
[assembly: AssemblyDescriptionAttribute("")]
[assembly: AssemblyCompanyAttribute("Castle Project")]
[assembly: AssemblyProductAttribute("Castle.MonoRail.TestSupport")]
[assembly: AssemblyCopyrightAttribute("Apache License, Version 2.0")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("1.0.0.2387")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: AssemblyKeyFileAttribute("../../CastleKey.snk")]
[assembly: AssemblyDelaySignAttribute(false)]

